/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_museum_server_GStreamer */

#ifndef _Included_com_museum_server_GStreamer
#define _Included_com_museum_server_GStreamer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_museum_server_GStreamer
 * Method:    runGstreamer
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_museum_server_GStreamer_runGstreamer
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     com_museum_server_GStreamer
 * Method:    killGst
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_museum_server_GStreamer_killGst
  (JNIEnv *, jobject);

/*
 * Class:     com_museum_server_GStreamer
 * Method:    setPathGst
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_museum_server_GStreamer_setPathGst
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
