/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jnidemojava_Main */

#ifndef _Included_jnidemojava_Main
#define _Included_jnidemojava_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jnidemojava_Main
 * Method:    nativePrint
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jnidemojava_Main_nativePrint
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
